Fiche film
WildCodeSchool/p2-g2-sept21-lille-react-Videotheque pull request #18
Opened 2021-11-05 15:22 UTC by BenZen59

2021-11-08 09:19 UTC, BBriset requested changes
some fix to do :)

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.css
> +body {
That body color broke the general background when its assembled with the main page

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.css
> +  -webkit-box-shadow: inset 0px 2px 50px 13px #000000;
double code for the same effect

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.css
> +  background: -moz-linear-gradient(top, rgb(0, 0, 0, 0.5) 0%, #eee8ec 20%, #fff 100%);
some double code

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.css
> +  background: -webkit-linear-gradient(top, rgb(0, 0, 0, 0.5) 0%, #eee8ec 20%, #fff 100%);
same

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.css
> +  -webkit-transform: scale(1.31);
Same four line who does the same thing

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.jsx
> +          <div className="numberVote">{numberVote} votes</div>
div cant be in a p

2021-11-08 09:19 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.jsx
>          console.error('Erreur API');
no console on dev branch

2021-11-08 09:23 UTC, BenZen59 commented on src/components/FicheFilm/FicheFilm.css
> +  -webkit-box-shadow: inset 0px 2px 50px 13px #000000;
Double to adapt for all bowser

2021-11-08 09:24 UTC, BenZen59 commented on src/components/FicheFilm/FicheFilm.css
> +  background: -moz-linear-gradient(top, rgb(0, 0, 0, 0.5) 0%, #eee8ec 20%, #fff 100%);
Double to adapt for all bowser

2021-11-08 09:24 UTC, BenZen59 commented on src/components/FicheFilm/FicheFilm.css
> +  background: -webkit-linear-gradient(top, rgb(0, 0, 0, 0.5) 0%, #eee8ec 20%, #fff 100%);
Double to adapt for all bowser

2021-11-08 09:24 UTC, BenZen59 commented on src/components/FicheFilm/FicheFilm.css
> +  -webkit-transform: scale(1.31);
Same

2021-11-08 09:26 UTC, BenZen59 commented on src/components/FicheFilm/FicheFilm.jsx
>          console.error('Erreur API');
fix later

2021-11-08 09:27 UTC, BenZen59 commented on src/components/FicheFilm/FicheFilm.css
> +body {
I retire this

2021-11-08 11:02 UTC, BBriset commented on src/components/FicheFilm/FicheFilm.css
> +body {
ok

2021-11-08 11:07 UTC, BBriset approved these changes, later dismissed
ok to me

2021-11-08 14:49 UTC, Hacene010 requested changes
The component is very long. when you code, make the components as short as possible. 
And don't use br : /

2021-11-08 14:49 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
>    const [title, setTitle] = useState([]);
If your state is an array then it must be on plural. Plz do it from line 13 to 22.

2021-11-08 14:49 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
> +  if (voteAverage === 10) {
You can do better and cleaner code here

2021-11-08 14:49 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
> +          <br />
No *br* use another method.

2021-11-10 14:47 UTC, Othmane-Khiter approved these changes

2021-11-15 08:59 UTC, Hacene010 approved these changes
Seems ok for me

2021-11-15 08:59 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
> +          <img className="starScore" src={Star()} alt="StarScore" />
I think you don't need to put the ''() " to Star.

2021-11-15 09:31 UTC, merged