Movie sheet
WildCodeSchool/p2-g2-sept21-lille-react-Videotheque pull request #22
Opened 2021-11-16 13:49 UTC by Quentin-Macquart

2021-11-16 15:12 UTC, BenZen59 approved these changes, later dismissed

2021-11-16 16:41 UTC, Hacene010 requested changes
seen some evils

2021-11-16 16:41 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.css
>  .titreVote {
Franglish ???

2021-11-16 16:41 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
> +  const [title, setTitle] = useState([]);
an array must be on plural (the same for all your states)

2021-11-16 16:41 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
>        <div className="titreVote">
franglish ???

2021-11-16 16:41 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
>            alt="fond"
is it in english or french ?

2021-11-16 16:41 UTC, Hacene010 commented on src/components/FicheFilm/FicheFilm.jsx
> +          <div className="buttonTrailer" alt="Trailer">
alt on camelCase like the others

2021-11-17 08:35 UTC, Othmane-Khiter approved these changes
ok

2021-11-17 09:29 UTC, Hacene010 approved these changes
that's better

2021-11-17 09:50 UTC, merged