Adding Route and links
WildCodeSchool/p2-g2-sept21-lille-react-Videotheque pull request #23
Opened 2021-11-16 15:08 UTC by BBriset

2021-11-16 15:11 UTC, BenZen59 approved these changes, later dismissed

2021-11-16 16:36 UTC, Hacene010 requested changes
Some changes to do

2021-11-16 16:36 UTC, Hacene010 commented on src/components/header/Header.jsx
> +            <li className=" menu-item">Watchlist</li>
camelCase plz

2021-11-16 16:36 UTC, Hacene010 commented on src/components/header/Header.jsx
> +              className="watchpage "
camelCase

2021-11-16 16:36 UTC, Hacene010 commented on src/components/header/Header.jsx
> +            className="Home"
camelCase

2021-11-16 16:36 UTC, Hacene010 commented on src/components/header/Header.jsx
> +                className="Home"
camelCase

2021-11-17 07:56 UTC, BenZen59 approved these changes

2021-11-17 09:28 UTC, Hacene010 approved these changes
that's better

2021-11-17 09:51 UTC, merged