Header
WildCodeSchool/p2-g2-sept21-lille-react-Videotheque pull request #3
Opened 2021-10-28 14:19 UTC by BBriset

Static header

2021-10-28 14:32 UTC, Quentin-Macquart approved these changes
Long to read, but it's seems ok to me.

2021-10-28 15:30 UTC, Hacene010 requested changes
No css on the xml file

2021-10-28 15:30 UTC, Hacene010 commented on src/components/header/Header.jsx
> +      <Menu width="40%" className="menu">
No style on the xml file :/

2021-10-28 18:18 UTC, BBriset commented
not really css it's a props of the component from the node module, i don't find out another way to change this its fixed by default at 300 px... 

Width

You can specify the width of the menu with the width prop. The default is 300.

Menu.defaultProps = {
        bodyClassName: '',
        burgerBarClassName: '',
        burgerButtonClassName: '',
        className: '',
        crossButtonClassName: '',
        crossClassName: '',
        disableAutoFocus: false,
        disableCloseOnEsc: false,
        htmlClassName: '',
        id: '',
        itemClassName: '',
        itemListClassName: '',
        menuClassName: '',
        morphShapeClassName: '',
        noOverlay: false,
        noTransition: false,
        onStateChange: function onStateChange() {
        },
        outerContainerId: '',
        overlayClassName: '',
        pageWrapId: '',
        styles: {},
        width: 300,
        onIconHoverChange: function onIconHoverChange() {
        },
        itemListElement: 'nav'
    };
    return Menu;

2021-10-29 07:09 UTC, Hacene010 commented
Ok Bertrand I did not see it like that

2021-10-29 07:11 UTC, Hacene010 approved these changes

2021-10-29 07:28 UTC, merged